### PR TITLE
Remove benches

### PR DESCRIPTION
**Pull request by rfuest**
Thank you for helping out with embedded-graphics-simulator development! Please:

- [ ] Check that you've added passing tests and documentation
- [ ] Add an example where applicable
- [ ] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, etc) if your changes affect the **public API**
- [ ] Run `rustfmt` on the project
- [ ] Run `just build` (Linux/macOS only) and make sure it passes. If you use Windows, check that CI passes once you've opened the PR.

## PR description

This PR removes the benches, that were moved to the main e-g crate, from this crate.

### CODE REVIEW

**Review by jamwaffles — CHANGES_REQUESTED** [review]
I realise this is still WIP, but in case you just forgot to tag me for a review: there are still some bench-related commands in the justfile. Otherwise LGTM :)

**Comment by rfuest** [comment]
I did forget to request the review, because I got distracted by doing other changes. Good catch with the justfile!

**Review by jamwaffles — APPROVED** [review]
I don't have a day job or a house. It's just me under a bridge with a Commodore 64 somehow running Firefox, mashing <kbd>F5</kbd> on the Github notifications page all day.

**Comment by rfuest** [comment]
I recently upgraded to a dual processor C128 and with the 2 MHz mode recompiling e-g only takes a week now :wink:. But I hope this new Ryzen 5000 stuff the kids talk about will be available to buy at reasonable prices soon.

Thanks for the review!

**Comment by jamwaffles** [comment]
I'll let you know! I'm going to trade in my C64 for a 5900X next week.

**Comment by rfuest** [comment]
I won't give up any of my C64s, but I'm also planning to buy a 5900X. I think that should make rust development far more enjoyable than on my i5-3570K from 8 years ago.

**Comment by jamwaffles** [comment]
:scream: so vintage! I mean...

image

That's gonna feel goooood.

I'm on a 3800X at the moment so the upgrade is less needed, but I'm looking forward to waiting around even less :grin:

**Comment by rfuest** [comment]
> That's gonna feel goooood.

Judging by that chart, I bet it will. Until recently I didn't considered an update to be necessary, because most task still work surprisingly well. And TBH I was a bit shocked when I realized when I had bought the CPU. But especially for larger rust projects it got more and more annoying recently.

**Pull request merged**
