### PR TITLE
Remove docs directory and update deps

### PR DESCRIPTION
**Pull request by rfuest**
This PR removes the `docs` directory, removes the `tinybmp` and `tinytga` dependencies and updates e-g to `0.7-alpha.3`.

### CODE REVIEW

**Comment by rfuest** [comment]
@jamwaffles Could you try to run `just build` locally and check if the link check fails?

The build fails locally, because of a broken link in `crossbeam_epoch/atomic/trait.Pointable.html`, but this isn't detected in CI. In this case this is an advantage, because we cannot easily fix that link in a different crate, but there might also be false negatives if the behavior in CI is different. I haven't checked which minor version of `cargo-deadlinks` 0.6 is included in the CI image, but perhaps that could be the difference. I'm using `0.6.2` locally.

**Comment by jamwaffles** [comment]
> I haven't checked which minor version of cargo-deadlinks 0.6 is included in the CI image

```
$ docker run --rm -it jamwaffles/circleci-embedded-graphics:1.40.0-2 cargo deadlinks --version
cargo-deadlinks 0.6.2
```

I get the same crossbeam doc errors locally using `deadlinks` 0.6.2 as well. `cargo update` doesn't change anything.

`deadlinks` 0.8.0 however does pass locally, although that needs a much more recent version of Rust to install. Should we consider raising the MSRV of both e-g-sim and e-g? I know we've thrown it back and forth a few times now, but there is a growing list of reasons to bump it. I don't know what MSRV deadlinks 0.8.0 needs.

That said, I don't think bumping the MSRV would help the CI/local disparity...

**Review by jamwaffles — APPROVED** [review]
Other than the CI issue, the changes themselves look good to me.

**Comment by rfuest** [comment]
> `deadlinks` 0.8.0 however does pass locally, although that needs a much more recent version of Rust to install. Should we consider raising the MSRV of both e-g-sim and e-g? I know we've thrown it back and forth a few times now, but there is a growing list of reasons to bump it. I don't know what MSRV deadlinks 0.8.0 needs.

The two Rust versions are independent of each other since we moved to a multi-stage Dockerfile some time ago. The tools are currently build using `1.48.0`. Could you bump the deadlinks version and publish a new docker image?

> That said, I don't think bumping the MSRV would help the CI/local disparity...

I just noticed that we haven't updated to the current docker image in `config.yml`, which explains the disparity.

**Pull request merged**
